list:
  path: /
  controller: App\Controller\Web\Admin\UserAdminController::list
  methods: ['GET']

timeline:
  path: /{id}/timeline
  controller: App\Controller\Web\Admin\UserAdminController::timeline
  methods: ['GET']

account_privacy:
  path: /{id}/account-privacy
  controller: App\Controller\Web\Admin\UserAdminController::accountPrivacy
  methods: ['GET']

edit_profile:
  path: /{id}/edit-user-profile
  controller: App\Controller\Web\Admin\UserAdminController::editUserProfile
  methods: ['GET', 'POST']